### PR TITLE
updating documentation

### PR DESCRIPTION
**Pull request by raymendozajr**
PR to update documentation with more detail in the README.  I'm putting both Adrienne and Ruben on this so you can both check out how to approve my changes.

Please leave me your comments and let me know if I've left anything out.  I'll continue to add new useful information to this readme as we go along.

### CODE REVIEW

**Review by aaustin56 — COMMENTED** [review]
Very thorough, thanks for the changes Ray.

**Comment by raymendozajr** [comment]
> Very thorough, thanks for the changes Ray.

Thanks Adrienne!  Have you submitted your review?  Not exactly sure how it works as I requested multiple reviewers and it said it required 1 approving review to merge changes.  Not sure where it says whether you've approved or it, or just that it showed the comment.

@Rbncrnj Can you take a look as well?

**Review by aaustin56 — APPROVED** [review]
Very good.

**Comment by raymendozajr** [comment]
Thanks for merging this as well @aaustin56 .  Let's work on some flow-control!  I'll delete this branch.

**Pull request merged**
